services:
  postgres:
    image: postgres:15-alpine
    container_name: testimonials-db
    environment:
      POSTGRES_DB: testimonials
      POSTGRES_USER: testimonials
      POSTGRES_PASSWORD: testimonials_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - testimonials-network

  backend:
    build: ./app/backend
    container_name: testimonials-api
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://testimonials:testimonials_password@postgres:5432/testimonials
      ADMIN_PASSWORD: admin123
      # Rate limiting configuration
      RATE_LIMIT_ENABLED: "false"        # Set to "false" to disable for testing
      RATE_LIMIT_WINDOW_MS: "3600000"    # 1 hour in milliseconds
      RATE_LIMIT_MAX: "3"                # Max submissions per window
    ports:
      - "3001:3001"
    volumes:
      - ./app/backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - testimonials-network
    command: npm run dev

  frontend:
    image: nginx:alpine
    container_name: testimonials-frontend
    ports:
      - "3000:80"
    volumes:
      - ./app/frontend/public:/usr/share/nginx/html
      - ./app/frontend/public/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - testimonials-network

  admin:
    build: ./app/frontend/admin
    container_name: testimonials-admin
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - testimonials-network

volumes:
  postgres_data:

networks:
  testimonials-network:
    driver: bridge